# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
        auth:
          username: nnenkov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test
      - store_test_results:
          path: ./test_reports/
      - store_artifacts:
          path: ./coverage/
      - run:
          name: Build project for prod
          command: npm run build
      - store_artifacts:
          path: ./dist/
      - setup_remote_docker
      - run:
          name: Check docker version
          command: docker -v
      - run:
          name: Build docker image
          command: docker build -t nnenkov/tsai-app .
      - run:
          name: Push docker image to artifactory
          command: docker push nnenkov/tsai-app
