# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm install -g jest && jest --config jest.config.ts --collectCoverage=true --runInBand
      - store_artifacts:
          path: coverage