# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run: npm install
      - run:
          name: Install JEST, TS-node and JUnit coverage reporter
          command: npm install -g jest && npm install -g ts-node && npm install -g jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: jest --config jest.config.ts --collectCoverage=true --runInBand --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      