# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: node:16-alpine
        auth:
          username: nnenkov
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run tests with JUnit as reporter
          command: jest --config jest.config.ts --collectCoverage=true --runInBand --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test_reports/
      - run:
          name: Build project for prod
          command: npm run build
      - store_artifacts:
          path: ./dist/
      - setup_remote_docker:
          version: 19.03.13
#          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build -t nnenkov/tsai-app .
      - run:
          name: Push docker image to artifactory
          command: docker push nnenkov/tsai-app
